version: 1.2

workflows:
  - name: OutlierExclusion
    subclass: WDL
    primaryDescriptorPath: /wdl/OutlierExclusion.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/

workflows:
  - name: OutlierExclusionScattered
    subclass: WDL
    primaryDescriptorPath: /wdl/OutlierExclusionScattered.wdl
    filters:
      branches:
        - main
      tags:
        - /.*/
